### ISSUE TITLE
Pass more arguments to update/insert functions

### ISSUE THREAD

**Issue by jridgewell** [thumbsupep/proposal-upsert#8]
Eg, the associated `key` and possibly the `map` instance. This can allow us to hoist the functions out instead of re-creating closures every time.

**Comment by bmeck** [comment]
@jridgewell do you have a preferred arg ordering, we could match `Array` methods maybe?

**Comment by jridgewell** [comment]
Yah, matching `Array.p.map` would be good. So:

- Updater: `(oldValue: T, key: K, map: Map) => T`
- Inserter: `(key: K, map: Map) => T`

**Comment by bmeck** [comment]
@jridgewell `Array.from` includes the "old" value as well, should we drop that from `insert?` if we do that it doesn't really match.

**Comment by jridgewell** [comment]
Are you saying we'd pass `oldValue` as the first parameter to `inserter`? It wouldn't be the end of the world, but I don't think consistency is necessary there.

If we do it, it brings up the "why are there two functions?" argument again. As in, someone would just check if `oldValue === undefined` to determine if we're inserting or updating in a single function.

**Comment by bmeck** [comment]
`undefined` is a valid value in a `Map` so you still wouldn't know if it already existed. That would be a weird scenario where `updater` would essentially potentially see the same argument set as `inserter` at times.
